repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^(\.github/workflows/|pipelines/)
      - id: end-of-file-fixer
      - id: detect-private-key
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.109.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
